# Generated by Django 6.0.8 on 2026-09-19 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('max_price_change_percent', models.DecimalField(decimal_places=4, default=10, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'price_categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='price.category')),
            ],
            options={
                'db_table': 'price_assets',
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SourceAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=1000)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('request_script', models.JSONField(blank=True, default=dict, help_text='تنظیمات داینامیک درخواست HTTP. امکان تنظیم headers، query، body، form، raw_body و content_type.')),
                ('header_token', models.CharField(blank=True, max_length=1000)),
                ('filter_field', models.CharField(blank=True, max_length=255)),
                ('filter_value', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='price.asset')),
            ],
            options={
                'db_table': 'price_source_apis',
                'ordering': ('asset__priority', 'asset__name', 'priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('time_unix', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='price.asset')),
                ('source_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='price.sourceapi')),
            ],
            options={
                'db_table': 'price_history',
                'ordering': ('-time_unix',),
                'indexes': [models.Index(fields=['asset', '-time_unix'], name='price_history_asset_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('time_unix', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_prices', to='price.asset')),
                ('source_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_prices', to='price.sourceapi')),
            ],
            options={
                'db_table': 'price_current_prices',
                'constraints': [models.UniqueConstraint(fields=('asset', 'source_api'), name='unique_current_price_asset_source')],
            },
        ),
        migrations.CreateModel(
            name='SourceAPIMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_field', models.CharField(choices=[('price', 'Price'), ('time_unix', 'Time Unix')], max_length=50)),
                ('source_path', models.CharField(help_text='مسیر فیلد در JSON. مثال: price یا data.price', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('source_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='price.sourceapi')),
            ],
            options={
                'db_table': 'price_source_api_mappings',
                'ordering': ('target_field',),
                'constraints': [models.UniqueConstraint(fields=('source_api', 'target_field'), name='unique_source_api_target_field')],
            },
        ),
    ]
